version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: week4
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -c log_statement=all

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
      - redis:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: >-
        order_events:3:1,
        completed_orders:3:1
    ports:
      - 9092:9092
    expose:
      - 9093
      - 9092
    volumes:
      - kafkadata:/kafka
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zkdata:/data
      - zkdatalog:/datalog
      - zklogs:/logs

volumes:
  dbdata:
  redisdata:
  redis:
  kafkadata:
  zkdata:
  zkdatalog:
  zklogs:
