global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
        
  - job_name: "customer-service"
    static_configs:
      - targets: [ "customer-service:5004" ]
    