version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: week4
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -c log_statement=all

volumes:
  dbdata:
