version: "3"
services:
  postgres:
    image: postgres:10
    container_name: workshop6
    restart: always
    environment:
      - "PGDEBUG=true"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=workshop6"
      - "PGSSLMODE=disable"
    ports:
      - 6432:5432